branch-defaults:
  master:
    environment: wire-website-gatsby
deploy:
  artifact: dist/elasticbeanstalk-nodejs-app.zip
environment-defaults:
  wire-website-gatsby:
    branch: null
    repository: null
global:
  application_name: Website
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
